// <auto-generated />
namespace TaskList.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DA2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DA2));
        
        string IMigrationMetadata.Id
        {
            get { return "201610271909118_DA2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
